# Streamlit Cloud secrets configuration
# Add your secrets here in the Streamlit Cloud dashboard

# OpenAI Configuration
OPENAI_API_KEY = "your_openai_api_key_here"
OPENAI_ASSISTANT_ID = "your_assistant_id_here"

# Document Database Path (will be set to cloud path)
DOCUMENT_DATABASE_PATH = "./Document Database"
